### ISSUE TITLE
Issues in package.json

### ISSUE THREAD

**Issue by humphd** [nguyenhung15913/OSD600-SSG#6]
The package.json file has a few issues:

1. Wrong License is used, based on LICENSE file, https://github.com/nguyenhung15913/OSD600-SSG/blob/main/package.json#L14 (should be MIT)
2. Package `name` doesn't match the project name https://github.com/nguyenhung15913/OSD600-SSG/blob/main/package.json#L2
3. Package author and description are missing

**Comment by nguyenhung15913** [comment]
Thanks for your feedbacks
