### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by humphd** [nguyenhung15913/OSD600-SSG#8]
You have various cases where you handle errors, and one of two approaches is used:

1. Log a message https://github.com/nguyenhung15913/OSD600-SSG/blob/main/osdssg.js#L67
2. Throw an error https://github.com/nguyenhung15913/OSD600-SSG/blob/main/osdssg.js#L82

Both can be improved and combined a bit.  When you have a non-fatal error, you can swallow the error and keep going.  However, if the error is fatal, you should end the program immediately:

- log a useful error message
- exit the process with a non-zero exit code using `process.exit(1)`

Throwing an error isn't really helpful if all you'll do is throw it up to the main thread, where the user will get it and the program crash.  You want to give them feedback so they can correct their mistake.

**Comment by nguyenhung15913** [comment]
Fixed and still testing

**Comment by humphd** [comment]
Great!  Feel free to close this when you're happy with it and it's working well.
